export type Locale = "en" | "es";

export const copy = {
  en: {
    metaDescription:
      "A Design Challenge in collaboration with Fab Lab Barcelona and OCAD University",
    season: "2026 – 2027 (pilot)",
    collaboration: "In collaboration with",
    becomeLine1: "Become a",
    becomeLine2: "partner",
    becomeLabel: "Become a partner",
    discover: "Discover",
    join: "Join the challenge",
    joinLine1: "Join the",
    joinLine2: "challenge",
    partner: "Partner",
    menu: "Menu",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    involved: "Get involved",
    language: "Language",
    scrollMore: "Scroll for more",
    soda: {
      kicker: "What is SOD+A?",
      title: "Schools of Discovery + Action",
      body: "SOD+A stands for Schools of Discovery + Action. It is an international design challenge where students explore ideas through creative uses of technology, share knowledge and collaborate with students in other communities, then bring their different skills and discoveries together to co-design a project that makes a lasting contribution locally.",
      quote: "You may be working locally, but knowledge is global.",
    },
    schools: {
      kicker: "Participating schools",
    },
    challenge: {
      kicker: "What is the challenge?",
      title: "See how far you can take an idea",
      body: "The challenge is to see how far you can take an idea: experiment, learn new skills, get feedback, make changes, share what you discover, put it into action, and meet criteria set by partner institutions. Along the way, you build a portfolio and develop the creative, technical, and human skills universities and innovative organizations are looking for.",
    },
    who: {
      kicker: "Who is it for?",
      title: "Students who want to make things with others",
      body: "SOD+A is for students in schools, makerspaces, or Fab Labs interested in engineering, entrepreneurship, digital and product design, creative direction, project management, art and technology, or any field where ideas, initiative, collaboration, and community engagement matter.",
    },
    why: {
      kicker: "Why?",
      title: "The hidden side of innovation",
      p1: "School gives you knowledge, skills, and structure. The SOD+A Challenge asks you to experience the hidden side of innovation: creativity, resilience, judgement, collaboration, and the ability to dive deeply into interests, technologies, and ideas that can have a positive impact.",
      p2: "You build a portfolio that makes your process, decisions, and growth visible, while receiving feedback and recognition from partner schools and organizations that value these skills. It is a chance to get noticed while having fun, discovering what you can do, and learning what it means to bring your talents into the world.",
    },
    how: {
      kicker: "How does it work?",
      title: "Join a local group. Share a global process.",
      p1: "You join a local group and identify a project you can co-design in your community. Then you head into a studio, lab, classroom, makerspace, or other creative space to experiment with ideas, materials, and technologies.",
      p2: "Curated random prompts and creative constraints push you toward unexpected combinations, new skills, and ideas you may not have explored on your own.",
      p3: "Along the way, you document and share what you learn, see what students in other communities are discovering, receive feedback, make changes, and bring your discoveries back into the collective project.",
      p4: "The challenge is to keep developing your ideas, share what you know, respond to feedback, put your learning into action, and meet the criteria set by partner institutions.",
    },
  },
  es: {
    metaDescription:
      "Un reto de diseño en colaboración con Fab Lab Barcelona y OCAD University",
    season: "2026 – 2027 (piloto)",
    collaboration: "En colaboración con",
    becomeLine1: "Hazte",
    becomeLine2: "partner",
    becomeLabel: "Hazte partner",
    discover: "Descubre",
    join: "Únete al reto",
    joinLine1: "Únete al",
    joinLine2: "reto",
    partner: "Partner",
    menu: "Menú",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    involved: "Participa",
    language: "Idioma",
    scrollMore: "Sigue bajando",
    soda: {
      kicker: "¿Qué es SOD+A?",
      title: "Schools of Discovery + Action",
      body: "SOD+A significa Schools of Discovery + Action (Escuelas de Descubrimiento + Acción). Es un reto internacional de diseño en el que el estudiantado explora ideas a través de usos creativos de la tecnología, comparte conocimiento y colabora con estudiantes de otras comunidades, y luego reúne distintas habilidades y descubrimientos para co-diseñar un proyecto que deje una contribución duradera en lo local.",
      quote: "Puedes estar trabajando en lo local, pero el conocimiento es global.",
    },
    schools: {
      kicker: "Escuelas participantes",
    },
    challenge: {
      kicker: "¿Qué es el reto?",
      title: "A ver hasta dónde puedes llevar una idea",
      body: "El reto consiste en ver hasta dónde puedes llevar una idea: experimentar, aprender nuevas habilidades, recibir comentarios, hacer cambios, compartir lo que descubres, ponerlo en práctica y cumplir los criterios de las instituciones colaboradoras. Por el camino, construyes un portafolio y desarrollas las habilidades creativas, técnicas y humanas que buscan las universidades y las organizaciones innovadoras.",
    },
    who: {
      kicker: "¿Para quién es?",
      title: "Estudiantes que quieren crear con otras personas",
      body: "SOD+A es para estudiantes de escuelas, makerspaces o Fab Labs interesados en ingeniería, emprendimiento, diseño digital y de producto, dirección creativa, gestión de proyectos, arte y tecnología, o cualquier campo en el que importen las ideas, la iniciativa, la colaboración y el compromiso con la comunidad.",
    },
    why: {
      kicker: "¿Por qué?",
      title: "El lado oculto de la innovación",
      p1: "La escuela te da conocimiento, habilidades y estructura. El Reto SOD+A te pide vivir el lado oculto de la innovación: creatividad, resiliencia, criterio, colaboración y la capacidad de profundizar en intereses, tecnologías e ideas que pueden tener un impacto positivo.",
      p2: "Construyes un portafolio que hace visible tu proceso, tus decisiones y tu crecimiento, mientras recibes comentarios y reconocimiento de escuelas y organizaciones colaboradoras que valoran estas habilidades. Es una oportunidad de que te vean, de divertirte, de descubrir lo que puedes hacer y de aprender lo que significa llevar tu talento al mundo.",
    },
    how: {
      kicker: "¿Cómo funciona?",
      title: "Únete a un grupo local. Comparte un proceso global.",
      p1: "Te unes a un grupo local e identificas un proyecto que puedas co-diseñar en tu comunidad. Luego entras a un estudio, laboratorio, aula, makerspace u otro espacio creativo para experimentar con ideas, materiales y tecnologías.",
      p2: "Indicaciones aleatorias curadas y restricciones creativas te empujan hacia combinaciones inesperadas, nuevas habilidades e ideas que quizá no habrías explorado por tu cuenta.",
      p3: "Por el camino, documentas y compartes lo que aprendes, ves lo que descubren estudiantes de otras comunidades, recibes comentarios, haces cambios y llevas tus descubrimientos de vuelta al proyecto colectivo.",
      p4: "El reto es seguir desarrollando tus ideas, compartir lo que sabes, responder a los comentarios, poner el aprendizaje en práctica y cumplir los criterios de las instituciones colaboradoras.",
    },
  },
} as const;
